{% set name = "pawflim" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pawflim-{{ version }}.tar.gz
  sha256: cf02d1ce185fedf9c15be669e693389b68a4dd576769fd47cda2288465085154

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - binlets >=1
    - numpy
    - scipy

test:
  imports:
    - pawflim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/maurosilber/pawflim/
  summary: Denoising via adaptive binning for FLIM datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maurosilber
